language: perl
perl:
  - "5.18"
sudo: required
 
install:
##Install SSL
  - sudo apt-get update
  - sudo apt-get install libssl1.0.0 libssl-dev libcrypto++9 libcrypto++-dev
  - cd /lib/x86_64-linux-gnu
  - sudo ln -s libssl.so.1.0.0 libssl.so.10
  - sudo ln -s libcrypto.so.1.0.0 libcrypto.so.10
  - cd -

## Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

script:
## Run MIP install script
  - wget https://github.com/J35P312/SVDB/archive/2.0.0.zip
  - unzip 2.0.0.zip
  - cd SVDB-2.0.0
  - pip install -e .
  - svdb --help
